import type { Metadata } from 'next';

// These styles apply to every route in the application
import './output.css';
// import './globals.css';
import { NextUIProvider, Navbar } from '@nextui-org/react';
import Layout from 'src/components/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="vsc-initialized">
        <>
          {children}
        </>
      </body>
    </html>
  );
}
